### ISSUE TITLE
Blocks break to easily.

### ISSUE THREAD

**Issue by CaptainStalfoss** [Stapleton/Stapletons-Ores#1]
The Blocks get destroyed in one hit by hand.
How do you change this? As far as i can see, there isn't any config file in the mod.

i can edit ingots and smelting myself, but i can't change the block resistance.

i'm not to picky, but i just want the blocks to at least work/break like regular Iron ore.

**Comment by Stapleton** [comment]
No worries! I probably just forgot to set the hardness. Give me a bit and I can have a new version with the fix.

**Comment by Stapleton** [comment]
I have added the default iron ore hardness to all ores. I am implementing configs for every ore so you can edit the hardness and resistance per ore to your liking. I may add some other options such as making the textures dynamically work with texture packs and some other stuff

--
Taylor Stapleton(587) 447-9036

OscarXcore/Stapletons-Ores wrote:

The Blocks get destroyed in one hit by hand.
How do you change this? As far as i can see, there isn't any config file in the mod.

i can edit ingots and smelting myself, but i can't change the block resistance.

i'm not to picky, but i just want the blocks to at least work like regular Iron ore.

**Comment by Stapleton** [comment]
I need to head to work. Here is the update with the fix since I dont have the time to publish to curseforge this minute.

http://teamcity.taylorstapleton.ca:8111/repository/download/MinecraftMods_StapletonsOres/2:id/stapletonsores-1.1.2.jar

**Comment by CaptainStalfoss** [comment]
That's awesome man, Thanks a lot.
Can't download from Teamcity, so i'll wait for your update on Curseforge.
But thank you very much, this saves me a lot of trouble.

**Comment by Stapleton** [comment]
No worries. I am home from work so I will publish the update here soon.
