### ISSUE TITLE
Ore Hardness

### ISSUE THREAD

**Issue by CaptainStalfoss** [Stapleton/Stapletons-Ores#2]
Hi, Me again, Love your mod since it has helped me a lot with the amount of ores it has.

however lately i wanted to have an unbreakable block for a reason, and since your mod now has configs, i figured i would use one of the Ores.

Sadly the config didn't effect the block, it still is mine-able like normal.

here's the setting i used: (i didn't change anything else in the config)

# Material config for Beryllium
##########################################################################################################

"ore settings" {
    # 'Actual Resistance' = 'Block Resistance' * 3
    # 
    #  [range: 0 ~ 10, default: 5]
    I:"Block Resistance"=10

    # if ('Actual Resistance' < 'Ore Hardness' * 5)
    # { 'Actual Resistance' = 'Ore Hardness' * 5 }
    # else { 'Actual Hardness' = 'Ore Hardness' }
    # 
    # Note: -1 Hardness is Unbreakable.
    #  [range: -1 ~ 10, default: 3]
    I:"Ore Hardness"=-1
}

**Comment by Stapleton** [comment]
So apparently I havent implemented that the config values do anything, because it needed a rewrite of how I register the ores, and my PC at the time of making the config system was trash. I can get it done over the next few days.

**Comment by Stapleton** [comment]
Fixed. 
https://tc.taylorstapleton.ca/repository/download/MinecraftMods_StapletonsOres/16:id/stapletonsores-1.1.3.jar

**Comment by CaptainStalfoss** [comment]
Awesome work! I appreciate it a lot, This mod has surprisingly been one of the most useful ones.
